// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_gG8ob5SC0Twfarbvl00uMkJ4SxH3FU',
    appId: '1:278558299485:web:553fe31e57e98e20b204b4',
    messagingSenderId: '278558299485',
    projectId: 'lexiaid-2e3b5',
    authDomain: 'lexiaid-2e3b5.firebaseapp.com',
    storageBucket: 'lexiaid-2e3b5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRVWdTlX9AyOx8T9U3B7XGO_DBad5p6Q',
    appId: '1:278558299485:android:94cc70f1eabb003fb204b4',
    messagingSenderId: '278558299485',
    projectId: 'lexiaid-2e3b5',
    storageBucket: 'lexiaid-2e3b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6pLaHQwO02gj1REhqxot_zMoSEj8eX8',
    appId: '1:278558299485:ios:128ce1e2b8a34196b204b4',
    messagingSenderId: '278558299485',
    projectId: 'lexiaid-2e3b5',
    storageBucket: 'lexiaid-2e3b5.firebasestorage.app',
    iosBundleId: 'com.nthucs.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN6pLaHQwO02gj1REhqxot_zMoSEj8eX8',
    appId: '1:278558299485:ios:c3081a108f60da39b204b4',
    messagingSenderId: '278558299485',
    projectId: 'lexiaid-2e3b5',
    storageBucket: 'lexiaid-2e3b5.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_gG8ob5SC0Twfarbvl00uMkJ4SxH3FU',
    appId: '1:278558299485:web:9a1505d2865455f2b204b4',
    messagingSenderId: '278558299485',
    projectId: 'lexiaid-2e3b5',
    authDomain: 'lexiaid-2e3b5.firebaseapp.com',
    storageBucket: 'lexiaid-2e3b5.firebasestorage.app',
  );

  
}